language: php

# Define the php versions against we want to test our code
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - master

# Note: Code coverage requires php-xDebug extension enabled on CI server

install:
  # Install composer packages
  - travis_retry composer install --no-interaction --no-suggest

# Create a storage folder for coverage report
before_script:
    - mkdir -p build/logs
    - ls -al

# Testing the app (see phpunit.xml) for configs, generating Code Coverage report
script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml


#after_script:


after_success:
# Submit coverage report to codecov.io
 - bash <(curl -s https://codecov.io/bash)

#after_failure:

# Tell Travis CI to monitor only 'master' branch
branches:
  only: master

# You can delete the cache using travis-ci web interface
cache:
  directories:
  - vendor
  - $HOME/.cache/composer